Remove monaco editor & let vscode render HTML & other mime types
AnWeber/httpbook pull request #29
Opened 2021-07-28 20:39 UTC by DonJayamanne

2021-07-28 20:42 UTC, DonJayamanne commented on src/extension/httpOutputProvider/builtInHttpOutputProvider.ts
> +        outputItems: vscode.NotebookCellOutputItem.json(JSON.parse(response.body)),
Let VS Code render JSON as well, special output item for that.

2021-07-28 20:43 UTC, DonJayamanne commented on src/extension/httpOutputProvider/builtInHttpOutputProvider.ts
> +        outputItems: vscode.NotebookCellOutputItem.text(response.body, mimeType),
All text outputs will be handled as `text/x-<language>`, if VS Codes doesn't know about the the language, then render as `text/plain`.

2021-07-29 04:51 UTC, AnWeber commented on src/extension/httpOutputProvider/builtInHttpOutputProvider.ts
> +      responseMimeType = 'texxt/javascript';
```suggestion
      responseMimeType = 'text/javascript';
```

2021-07-29 04:52 UTC, AnWeber commented on src/extension/extension.ts
> +    httpNotebookOutputFactory.initiailze();
Was the missing await intentional? 
```suggestion
    await httpNotebookOutputFactory.initialize();
```

2021-07-29 05:09 UTC, AnWeber requested changes
Thanks for the pull request. I'm afraid I didn't catch when vscode started offering x-{{lang}} notebookRenderer. If I have overlooked that initially, that would not be nice. I could have saved the fuss with monaco editor.
I will rebuild the `initialize` afterwards and initialize the languages lazy in `getResponseOutputResult`. I offer this method as interface for other extensions and promise is a good addition.
There are still two small places that would need to be adjusted and I will try it out after that.

2021-07-29 16:14 UTC, DonJayamanne commented on src/extension/extension.ts
> +    httpNotebookOutputFactory.initiailze();
Yes, I don't see any reason to wait do that. That'll complete very quickly, besides it'll take a bit longer for notebooks to open etc, hence no point in waiting.

Then again no harm on waiting as well. I think either is fine

2021-07-30 12:38 UTC, AnWeber commented
I will merge the pull request, however I am not entirely happy with the result in the current state of vscode. Monaco Editor has solved a few small problems for me.
* Missing search in output (microsoft/vscode#128665, microsoft/vscode#94239)
* no pretty print of output (solvable in extension)
* horizontal scrolling issue (microsoft/vscode#110825)
* broken renderer issue with css 
![image](https://user-images.githubusercontent.com/13434739/127654049-3c763647-259a-4fb6-8334-f5aa1968bddd.png)
* accessiblity issue with output end 
![image](https://user-images.githubusercontent.com/13434739/127652542-3170a5c1-d31a-484f-8946-afff3561485d.png)
* broken height of output cells (microsoft/vscode#126863, microsoft/vscode#128391)

For this reason, I will temporarily put the Monaco Renderer into its own extension, so that you can continue to use it if needed.

2021-07-30 12:38 UTC, merged